### PR TITLE
DC.2 Match species to trait databases to fill in chemical traits etc, until we get them.

### PR DESCRIPTION
**Pull request by TanyaS08**

### CODE REVIEW

**Comment by TanyaS08** [comment]
What has been done: 

I've only looked at BIEN and the only traits (as far as I can tell) available are C, N & P per leaf area and C:N so I've pulled those traits for species/families/genera where possible. I haven't check (and know for a fact) that there will be some traits that we don't have data for even at the family level.

So at this point we have none of the isotope traits and missing N:P. Not sure where to go next - thoughts?

**Comment by JocelynNavarro** [comment]
Hi Tanya,

I am glad you got a chance to use the BIEN database to access chemical traits. I can look at the missing traits that weren’t available on BIEN and try to access them through the TRY database. I also checked with Christine (lab manager in the Enquist Lab) and Brian Enquist and chemical traits are not done yet. 


Best,

Jocelyn

**Comment by TanyaS08** [comment]
I've added a .csv file with all the species x trait combos we still need. We can discuss this later today

**Comment by JocelynNavarro** [comment]
Sounds good! What zoom link should we use? 

See you soon! 

Jocelyn

**Comment by TanyaS08** [comment]
I've added the data from TRY (no N<sub>15</sub> isotope or C:P data and limited data for the other traits ~ 10 species and thats not even per a trait). Not sure how we should move forward? Maybe some dummy data where we have none just so that when people are working with the dataset they are at least aware of/'see' all the trait variable we will have at some point?

**Comment by TanyaS08** [comment]
Might be worth pulling together a coverage plot of sorts to get an idea of what is missing or nah?

**Comment by srg101** [comment]
Yeah, I wonder if just leaving ball-park figures for these chemical traits is just easy for now. I mean we don't plan to interpret these actual values right? So it's more to test if a given script will work more than anything?

**Comment by TanyaS08** [comment]
I've added C:P and N15 with random values form a normal distribution as well as supplementing the other missing chem traits data with random values from a normal dist based on the mean trait values. Basically the only question is should I write this as a data file that people can then call as opposed to having them have to run the entire script?

**Pull request merged**
